version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - '81:80'
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - projeto-php-estudando-ddd
    depends_on:
      - php-fpm
        
  php-fpm:
    build:
      context: .
    volumes:
      - ./:/var/www/html
    networks:
      - projeto-php-estudando-ddd
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4.2
    restart: always
    environment:
      MYSQL_DATABASE: projetophp
      MYSQL_ROOT_PASSWORD: root
    networks:
      - projeto-php-estudando-ddd
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin: 
    image: phpmyadmin:5.2
    restart: always
    ports: 
      - 82:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - projeto-php-estudando-ddd
    depends_on:
      db:
        condition: service_healthy

networks:
  projeto-php-estudando-ddd:
    driver: bridge


